language: cpp

compiler:
  - gcc

env:
  - LUA='Lua 5.2'

before_install:
  - bash .travis_setup.sh
  - cmake --version && g++ -v

install:
  - luarocks make
  - gem install coveralls-lcov json
  - sudo apt-get install libgtest-dev valgrind lcov
  - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"

before_script:
  - pwd && mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DTEST_COVERAGE=On ..

script: make testsuites && make test

after_success:
  - lcov --capture --directory src/core --output-file coverage_full.info
  - lcov --remove coverage_full.info "*/include/*" "*/generated/*" "*.l" "*.cc" -o coverage_clean.info
  - cd .. && coveralls-lcov build/coverage_clean.info
